services:
  auth-db:
    image: postgres:16
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  trips-db:
    image: postgres:16
    environment:
      POSTGRES_DB: trips
      POSTGRES_USER: trips
      POSTGRES_PASSWORD: trips
    ports:
      - "5434:5432"
    volumes:
      - trips_db_data:/var/lib/postgresql/data

  rec-db:
    image: postgres:16
    environment:
      POSTGRES_DB: recs
      POSTGRES_USER: recs
      POSTGRES_PASSWORD: recs
    ports:
      - "5435:5432"
    volumes:
      - rec_db_data:/var/lib/postgresql/data

  payments-db:
    image: postgres:16
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
    ports:
      - "5436:5432"
    volumes:
      - payments_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  auth-service:
    build:
      context: ../services/auth-service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg://auth:auth@auth-db:5432/auth
      JWT_SECRET: dev_secret
      JWT_ALG: HS256
    ports:
      - "8001:8000"
    depends_on:
      - auth-db

  trips-service:
    build:
      context: ../services/trips-service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg://trips:trips@trips-db:5432/trips
    ports:
      - "8002:8000"
    depends_on:
      - trips-db

  recommendations-service:
    build:
      context: ../services/recommendations-service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    depends_on:
      - rec-db
      - redis

  payments-service:
    build:
      context: ../services/payments-service
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    depends_on:
      - payments-db

volumes:
  auth_db_data:
  trips_db_data:
  rec_db_data:
  payments_db_data:
